### ISSUE TITLE
mobx + next + mongodb

### ISSUE THREAD

**Issue by ralphievolt** [fdidron/mobx-next-example#1]
Can you please create an additional example where the todo have a crud with a mongodb?

I'm totally new with MobX and find NextJs very interesting especially like me coming from  MeteorJs

**Comment by fdidron** [comment]
Hi @ralphievolt ,

I'm unfortunately not versed with MongoDB, I would assume the best way to do CRUD would be to first create a HTTP Rest service encapsulating your database, then plug it to Next / Mobx.

In that regard, I was planning to demo CRUD operations using Firebase (HTTP Rest Calls, not the SDK).

All you would have to do after is plug the demo to you own backend if you want to use mongodb.

**Comment by ralphievolt** [comment]
I can live with that example =) I am more interested from any data acquisition from the server-db down to client.

looking forward to it.

**Comment by fdidron** [comment]
Sorry for the lack of update. I just added CRUD operations + a demo here https://mobx-next.now.sh/
